accounts/urls.py
from django.conf.urls import url
from  accounts import views
from django.contrib.auth.views import login,logout
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    # url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name':'accounts/login.html'}),
    url(r'^logout/', views.logout_user, name = 'logout'),
    # url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$',views.register, name = 'register'),
#     url(r'^profile/$', views.user_profile, name = 'view_profile' ),
#     url(r'^profile/edit/$', views.edit_profile, name = 'edit_profile' ),
#     url(r'^change-password/$', views.change_password, name = 'change_password' )
# 
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

neighbors/urls.py
from django.conf.urls import url
from neighbors import views as neighbors_views
# from projects import views as project_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', neighbors_views.home, name = 'home'),
    url(r'^neighborhoods/$', neighbors_views.all_neighbors, name = 'all_neighbors'),
    # url(r'^neighborhoods/(?P<pk>\d+)/$', neighbors_views.neighborhood_details, name = 'hood-details'),
    url(r'^neighborhoods/(?P<id>\d+)/$', neighbors_views.neighborhood_details, name = 'hood-details'),

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

thewatch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.contrib.gis import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('neighbors.urls', namespace='neighbors')),
    url(r'^accounts/',include('accounts.urls', namespace='accounts')),

]

neighbors/models.py
from django.db import models
from django.contrib.auth.models import User
# from accounts.models import Profile




# Create your models here.


class Neighborhood(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length = 100)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    
    
    class Meta:
        verbose_name  = "Neighborhood"
        verbose_name_plural  = "Neighborhoods"
    
    def __str__(self):
        return f'{self.name}'
    
    
    def count_occupants(self):
        pass

class Business(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    
    
    class Meta:
        verbose_name = 'Business'
        verbose_name_plural = 'Businesses'

    
    def __str__(self):
        return f'{self.name}'
    
      
class Contact(models.Model):
    contact_type = models.CharField(max_length=70)# specifies whether its a fire, police, hosptial etc
    phone = models.CharField(max_length=12)
    email = models.EmailField()
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

    def __str__(self):
        return f'{self.contact_type}, {self.phone}'
    
    

class Post(models.Model):
    title = models.CharField(max_length=100)
    body  = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.title}'
    
    
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

neighbors/forms.py
from django import forms
from neighbors.models import Neighborhood, Business, Contact, Post

class AddNeighborhoodForm(forms.ModelForm):
    class Meta:
        
        model = Neighborhood
        fields = (
            'name',
            'location',
            'address',
            'city'
            )
    
    

class AddBusinessForm(forms.Form):
    class Meta:
        model = Business
        fields = (
            'name',
            'address',
            'city'
        )
        
class AddContactForm(forms.Form):
    class Meta:
        model = Contact
        fields = (
            'contact_type',
            'phone',
            'email',
            'neighborhood',
            'posted_by'
        )
        
        
class AddPostForm(forms.Form):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'author',
            'neighborhood',
            'pub_date'
        )

neighbors/views.py
from django.shortcuts import render, redirect, get_object_or_404
from neighbors.models import Neighborhood, Business, Contact, Post
from neighbors.forms import (AddBusinessForm, AddContactForm, 
                             AddNeighborhoodForm, AddPostForm)
from django.urls import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required

# Create your views here.


def home(request):
    # projects = Project.objects.all()
    
    # context = {
    #     "projects":projects
    # }
    
    title = "Neighbors"
    posts = Post.objects.all().order_by('-pub_date')[:3]
    hoods = Neighborhood.objects.all().order_by('id')[:3]
    business = Business.objects.all().order_by('id')[:3]
    
    
    return render(request, 'neighbors/index.html', {"title":title, "posts":posts, "hoods":hoods, "business":business})

@login_required
def all_neighbors(request):
    all_neighbors = Neighborhood.objects.all()
    
    return render(request, 'neighbors/neighborhoods.html', {"all_neighbors":all_neighbors})

def create_neighhood(request):
    current_user = request.user.profile
    
    form = AddNeighborhoodForm()
    if request.method =='POST':
        form = AddNeighborhoodForm(request.POST)
        if form.is_valid():
            hood = form.save(commit = False)
            hood.profile = current_user
            hood.save()
            return redirect(reverse('accounts:view_profile'))
        else:
            form = AddNeighborhoodForm()
            
    return render(request, 'neighbors/add_hood.html',{"form":form})






def neighborhood_details(request, id):
    hood_detail = Neighborhood.objects.get(pk=id)
    
    context = {
        'hood_detail':hood_detail
    }    
    return render(request, 'neighbors/neighborhoods_details.html', context)


def posts(request):
    posts = Post.objects.all()
    
    
    
    return render(request, 'neighbors/posts.html', {"posts":posts})

neighbors/templates/neighbors/add_post.html
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <div class="col-6 col-md-4">
        <form method="POST">
            {% csrf_token %} 
                {{form|crispy}}
            <button type="submit">Submit</button>    
        </form>
    </div>
</div>

neighbors/templates/neighbors/checkin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">

<div class="col-6 col-md-4" style="text-align: center">
<h2>Checkin</h2>

<form action = "/neighbors/show/"method="post">
    <h2> This is checkin page</h2>
    <!-- {% csrf_token %}
    {{form|crispy}}

    <button type="submit" class="btn btn-primary">Login</button>

    <p>Dont have an account? Sign up <span>here</span></p> -->
    <br>
    <br>
    <br>
    <br>

    <input placeholder ="name" type="text" id="username" name="username"> <br>
    <input placeholder ="password" type="text" id="userimage" name="userimage"><br>
    <input placeholder ="long" type="text" id="long" name="long"><br>
    <input placeholder ="lat" type="text" id="lat" name="lat"><br>
    <input type="submit" value="Submit">


</form>
</div>
    </div>
  
    
{% endblock %}

neighbors/templates/neighbors/details.html
{% extends 'base.html' %}

{% block content %}


<h2>Hood details</h2>


{% endblock %}

neighbors/templates/neighbors/index.html
{% extends 'base.html' %}


{% block content %}

<br>

    <div class="jumbotron" style="text-align: center">
        <h1 class="display-3">Neighborhood Watch</h1>
        <p class="lead"> You dont always get to know what is hapening in your hood! Well now, you cat catch all the updates right on this page.</p>

        <p class="lead"> Wanna know what's up? 
            <a class="btn btn-info btn-sm" href="{% url 'neighbors:all_neighbors'%}" role="button">Chekin here!</a>
          </p>
        <hr class="my-4">
      </div>

    <div class="container">

      <h4 style="text-align: center">Latest!</h4>
      <div class="row">
        
        <div class="col">
          <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0"><i class="fas fa-map-marker-alt"></i>  Newest Hoods!</h6>
            {% for hood in hoods %}
            <div class="media text-muted pt-3">
              <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{hood.name}}</strong>
                    {{hood.address}}              </p>
            </div>

            {% endfor %}
          </div>
        </div>
        <div class="col">
          <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0"><i class="fas fa-newspaper"></i>  News updates </h6>
            {% for post in posts %}
            <div class="media text-muted pt-3">
              <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#e83e8c"/><text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text></svg>
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">Author: {{post.author}}</strong>
                {{post.body}} <br>
                Posted: {{post.pub_date}}
              </p>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="col">
          <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0"><i class="fas fa-building"></i>  Businesses</h6>
            {% for biz in business %}
            <div class="media text-muted pt-3">
              <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#6f42c1"/><text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text></svg>
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{biz.name}}</strong>
              {{biz.neighborhood}}
              {{biz.address}}

              </p>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

{% endblock %}

neighbors/templates/neighbors/location.html
{% extends 'base.html'%}
{% load static %}




{% block content %}

<div class="split left">
    <div class="centered">

            <br>
    <br>
    <br>

        <h2> This is in for page</h2>

        {% if hoods %}

        {% for hood in hoods %}


        {{hood.name}}


        {% endfor %}


        {% endif %}

    </div>

</div>

</div>
{% endblock %}

neighbors/templates/neighbors/navbar.html
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'neighbors:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">


          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'neighbors:all_neighbors'%}">Neighborhoods</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
              <a class="nav-link" href="accounts/login/">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
              </li>

              {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

neighbors/templates/neighbors/neighborhoods.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<br>


<div class="container">
    <br>
    <h1 class="text-center pt-3"> Hey {{user.username}}, Select your hood!</h1>
    <br/>
    <br/>
    <hr>
    <div class="container" style="text-align: center ">
            <button type="button" class="btn btn-outline-primary">Add a neighborhood </button>
    </div>
    <br>

    
    <div class="album" style="align-content:stretch">
            <div class="container" style="text-align: center">
                <div class="row">
                {% if all_neighbors %}
                {% for hood in all_neighbors %}
                <div class="card bg-light mb-3" style="max-width: 20rem;">

                <div class="card-header"> {{hood.name}}</div>
                <div class="card-body">
                <h6 class="card-title">Address:{{hood.address}}</h6>
                <p class="card-text">City:{{hood.city}}</p>

                <a href="{{hood.id}}"class="btn btn-outline-primary">Checkin</a>
                </div>
                
                </div>
                {% endfor %}
                {% endif %} 
                </div>   
                  
            </div>
    </div>
            


{% endblock %}

neighbors/templates/neighbors/neighborhoods_details.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <br>
    <br>
    <h3 class="text-center pt-3">You are curently in {{hood_detail.name}} as {{user.username}}</h3>

</div>


      <div class="row">
        
        <div class="col">
          <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0"><i class="fas fa-tty"></i> Key Contacts</h6>
        
            <div class="media text-muted pt-3">
              <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">tststs</strong>
                                 </p>
            </div>

          </div>
        </div>
        <div class="col">
          <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0"><i class="fas fa-bullhorn"></i> News updates </h6>
           
            <div class="media text-muted pt-3">
              <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#e83e8c"/><text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text></svg>
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">Author:</strong>
                <br>
               
              </p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0"><i class="fas fa-shopping-cart"></i>  Businesses</h6>
            
            <div class="media text-muted pt-3">
              <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#6f42c1"/><text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text></svg>
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">ttete</strong>
             

              </p>
            </div>
          </div>
        </div>
      </div>
    </div>



    <br>
<div class="container" style="text-align: center ">
        <button type="button" class="btn btn-outline-primary">Add Contacts</button>
    <button type="button" class="btn btn-outline-secondary">Add Post</button>
    <button type="button" class="btn btn-outline-success">Add Bizz</button>
    <a href="{% url 'neighbors:all_neighbors'%}"class="btn btn-outline-warning">Checkout of {{hood_detail.name}}</a>
</div>

{% endblock %}

neighbors/templates/neighbors/posts.html
{% extends 'base.html' %}
{% block content %}

{% for post in posts %}

{{post.title}} <br>
{{post.pub_date}}<br>
{% endfor %}

{% endblock %}

{% endblock %}